app_name = 'erpnext_nextcloud_sso'
app_title = 'Nextcloud SSO'
app_publisher = 'b»robotized group'
app_description = 'Userinfo shim to use Nextcloud OAuth2 with ERPNext v16 social login.'
app_email = 'erp-devs@b-robotized.com'
app_license = 'MIT'
